import Head from 'next/head'
import Image from 'next/image'
import Sidebar from "../components/Sidebar"
import Feed from "../components/Feed"
import Widgets from "../components/Widgets"
  

type Props = {
  newsResults: string
  randomUsersResults: string
}

export default function Home ({newsResults, randomUsersResults }: Props) {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <main className="flex min-h-screen  mx-auto">
        {/* {Sidebar} */}
        <Sidebar/>
        {/* {Feeds} */}
          <Feed/>
        {/* {Widgets} */}

        <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results}/>

        {/* {Modal} */}
      </main>
    </>
  )
}



export async function getServerSideProps() {
  const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/health/us.json")
    .then((res) => res.json()) 

  const randomUsersResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture")
      .then((res) => res.json())
  return {
      props:{
          newsResults,
          randomUsersResults,
          
      }
  }
  
}